---
- name: Create a Virtual Machine on OpenShift Virtualization
  hosts: p1-local.chiaret.to
  gather_facts: false

  tasks:
    - name: Generate and create Virtual Machines with unique names
      ansible.builtin.include_tasks: create-vms-tasks.yaml
      with_sequence: count={{ n_vms }}

    - name: Wait for all VMs to be running
      kubernetes.core.k8s_info:
        kubeconfig: "/data/vms/clusters/{{ clustername }}/auth/kubeconfig"
        api_version: v1
        kind: VirtualMachineInstance
        namespace: "{{ vm_project }}"
      register: vmi_list
      until: vmi_list.resources | selectattr('status.phase', 'eq', 'Running') | list | length == vmi_list.resources | length
      retries: 30
      delay: 10
