---
- name: Create a Virtual Machine on OpenShift Virtualization
  hosts: p1-local.chiaret.to
  gather_facts: false

  tasks:
    - name: Generate and create Virtual Machines with unique names
      ansible.builtin.include_tasks: create-vms-tasks.yaml
      with_sequence: count={{ n_vms }}

    - name: Wait 20 seconds to create VMI
      ansible.builtin.pause:
        seconds: 20

    - name: Wait for all VMs to be running
      kubernetes.core.k8s_info:
        kubeconfig: "/data/vms/clusters/{{ clustername }}/auth/kubeconfig"
        api_version: v1
        kind: VirtualMachineInstance
        namespace: "{{ vm_project }}"
      register: vmi_list
      until: vmi_list.resources | selectattr('status.phase', 'eq', 'Running') | list | length == vmi_list.resources | length
      retries: 30
      delay: 10

    - name: Get all VirtualMachineInstances in the namespace
      kubernetes.core.k8s_info:
        kubeconfig: "/data/vms/clusters/{{ clustername }}/auth/kubeconfig"
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ vm_project }}"
        label_selectors:
          - "app = {{ app_name }}"
      register: vmi_list

    - name: Wait for the VM get an IP address
      kubernetes.core.k8s_info:
        kubeconfig: "/data/vms/clusters/{{ clustername }}/auth/kubeconfig"
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ vm_project }}"
        name: "{{ item }}"
      register: vmi_info
      until:
        - vmi_info.resources[0].status.interfaces[0].ipAddress is defined
        - vmi_info.resources[0].status.interfaces | selectattr('ipAddress', 'match', '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$') | length > 0
      retries: 30
      delay: 10
      with_items: "{{ vmi_list.resources | map(attribute='metadata.name') | list }}"

    - name: Getting VM IP addresses
      ansible.builtin.set_fact:
        vm_ips: "{{ vm_ips | default([]) + [item.resources[0].status.interfaces[0].ipAddress] }}"
      with_items: "{{ vmi_info.results }}"

    - name: Wait for port 8080 to be open on VM
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 8080
        timeout: 120
        state: started
      register: open_port_8080
      with_items: "{{ vm_ips }}"
      async: 180
      poll: 0

    - name: Creating service
      kubernetes.core.k8s:
        kubeconfig: "/data/vms/clusters/{{ clustername }}/auth/kubeconfig"
        state: present
        template: "service.yaml.j2"

    - name: Creating route
      kubernetes.core.k8s:
        kubeconfig: "/data/vms/clusters/{{ clustername }}/auth/kubeconfig"
        state: present
        template: "route.yaml.j2"
